#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.3 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Jun 14 22:48:03 CEST 2023
# SW Build 2405991 on Thu Dec  6 23:36:41 MST 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim tremolo_tb_behav -key {Behavioral:sim_1:Functional:tremolo_tb} -tclbatch tremolo_tb.tcl -protoinst "protoinst_files/audio_processing.protoinst" -view /home/maniek/Vivado/audio-effect-box/audio-effect-box.srcs/sim_1/new/delay_tb_behav.wcfg -log simulate.log
