# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param ced.repoPaths /mnt/HGST/Programy/Xilinx/ExampleProjects/XilinxCEDStore
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/maniek/Vivado/audio-effect-box/audio-effect-box.cache/wt [current_project]
set_property parent.project_path /home/maniek/Vivado/audio-effect-box/audio-effect-box.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_repo_paths {
  /home/maniek/Vivado/ip_repo/spi_master_1.0
  /home/maniek/git/audio-processing/pl/ip_repo
  /home/maniek/Vivado/ip_repo/ssd1306_driver_1.0
} [current_project]
update_ip_catalog
set_property ip_output_repo /home/maniek/Vivado/audio-effect-box/audio-effect-box.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/maniek/Vivado/audio-effect-box/audio-effect-box.srcs/sources_1/bd/audio_processing/ip/audio_processing_ssd1306_driver_0_0/ip/power_on_off_sequence.coe
read_verilog -library xil_defaultlib /home/maniek/Vivado/audio-effect-box/audio-effect-box.srcs/sources_1/bd/audio_processing/hdl/audio_processing_wrapper.v
add_files /home/maniek/Vivado/audio-effect-box/audio-effect-box.srcs/sources_1/bd/audio_processing/audio_processing.bd
set_property used_in_implementation false [get_files -all /home/maniek/Vivado/audio-effect-box/audio-effect-box.srcs/sources_1/bd/audio_processing/ip/audio_processing_clk_wiz_0_0/audio_processing_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/maniek/Vivado/audio-effect-box/audio-effect-box.srcs/sources_1/bd/audio_processing/ip/audio_processing_clk_wiz_0_0/audio_processing_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/maniek/Vivado/audio-effect-box/audio-effect-box.srcs/sources_1/bd/audio_processing/ip/audio_processing_clk_wiz_0_0/audio_processing_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/maniek/Vivado/audio-effect-box/audio-effect-box.srcs/sources_1/bd/audio_processing/ip/audio_processing_processing_system7_0_0/audio_processing_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/maniek/Vivado/audio-effect-box/audio-effect-box.srcs/sources_1/bd/audio_processing/ip/audio_processing_rst_ps7_0_50M_0/audio_processing_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/maniek/Vivado/audio-effect-box/audio-effect-box.srcs/sources_1/bd/audio_processing/ip/audio_processing_rst_ps7_0_50M_0/audio_processing_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all /home/maniek/Vivado/audio-effect-box/audio-effect-box.srcs/sources_1/bd/audio_processing/ip/audio_processing_rst_ps7_0_50M_0/audio_processing_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/maniek/Vivado/audio-effect-box/audio-effect-box.srcs/sources_1/bd/audio_processing/ip/audio_processing_xbar_0/audio_processing_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/maniek/Vivado/audio-effect-box/audio-effect-box.srcs/sources_1/bd/audio_processing/ip/audio_processing_ssd1306_driver_0_0/ip/power_on_off_sequence_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/maniek/Vivado/audio-effect-box/audio-effect-box.srcs/sources_1/bd/audio_processing/ip/audio_processing_axi_gpio_0_0/audio_processing_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/maniek/Vivado/audio-effect-box/audio-effect-box.srcs/sources_1/bd/audio_processing/ip/audio_processing_axi_gpio_0_0/audio_processing_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/maniek/Vivado/audio-effect-box/audio-effect-box.srcs/sources_1/bd/audio_processing/ip/audio_processing_axi_gpio_0_0/audio_processing_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/maniek/Vivado/audio-effect-box/audio-effect-box.srcs/sources_1/bd/audio_processing/ip/audio_processing_axi_gpio_0_1/audio_processing_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/maniek/Vivado/audio-effect-box/audio-effect-box.srcs/sources_1/bd/audio_processing/ip/audio_processing_axi_gpio_0_1/audio_processing_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/maniek/Vivado/audio-effect-box/audio-effect-box.srcs/sources_1/bd/audio_processing/ip/audio_processing_axi_gpio_0_1/audio_processing_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/maniek/Vivado/audio-effect-box/audio-effect-box.srcs/sources_1/bd/audio_processing/ip/audio_processing_auto_pc_0/audio_processing_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/maniek/Vivado/audio-effect-box/audio-effect-box.srcs/sources_1/bd/audio_processing/audio_processing_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/maniek/git/audio-processing/pl/src/constraints/audio-effect-box.xdc
set_property used_in_implementation false [get_files /home/maniek/git/audio-processing/pl/src/constraints/audio-effect-box.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top audio_processing_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef audio_processing_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file audio_processing_wrapper_utilization_synth.rpt -pb audio_processing_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
