# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/maniek/git/audio-processing/pl/src/constraints/audio-effect-box.xdc

# Block Designs: bd/audio_processing/audio_processing.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_processing || ORIG_REF_NAME==audio_processing} -quiet] -quiet

# IP: bd/audio_processing/ip/audio_processing_adau1761_controller_0_0/audio_processing_adau1761_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_processing_adau1761_controller_0_0 || ORIG_REF_NAME==audio_processing_adau1761_controller_0_0} -quiet] -quiet

# IP: bd/audio_processing/ip/audio_processing_clk_wiz_0_0/audio_processing_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_processing_clk_wiz_0_0 || ORIG_REF_NAME==audio_processing_clk_wiz_0_0} -quiet] -quiet

# IP: bd/audio_processing/ip/audio_processing_i2s_receiver_0_0/audio_processing_i2s_receiver_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_processing_i2s_receiver_0_0 || ORIG_REF_NAME==audio_processing_i2s_receiver_0_0} -quiet] -quiet

# IP: bd/audio_processing/ip/audio_processing_i2s_transmitter_0_0/audio_processing_i2s_transmitter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_processing_i2s_transmitter_0_0 || ORIG_REF_NAME==audio_processing_i2s_transmitter_0_0} -quiet] -quiet

# IP: bd/audio_processing/ip/audio_processing_processing_system7_0_0/audio_processing_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_processing_processing_system7_0_0 || ORIG_REF_NAME==audio_processing_processing_system7_0_0} -quiet] -quiet

# IP: bd/audio_processing/ip/audio_processing_ps7_0_axi_periph_0/audio_processing_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_processing_ps7_0_axi_periph_0 || ORIG_REF_NAME==audio_processing_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/audio_processing/ip/audio_processing_rst_ps7_0_50M_0/audio_processing_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_processing_rst_ps7_0_50M_0 || ORIG_REF_NAME==audio_processing_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/audio_processing/ip/audio_processing_stereo_to_mono_0_0/audio_processing_stereo_to_mono_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_processing_stereo_to_mono_0_0 || ORIG_REF_NAME==audio_processing_stereo_to_mono_0_0} -quiet] -quiet

# IP: bd/audio_processing/ip/audio_processing_xbar_0/audio_processing_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_processing_xbar_0 || ORIG_REF_NAME==audio_processing_xbar_0} -quiet] -quiet

# IP: bd/audio_processing/ip/audio_processing_sample_to_leds_0_0/audio_processing_sample_to_leds_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_processing_sample_to_leds_0_0 || ORIG_REF_NAME==audio_processing_sample_to_leds_0_0} -quiet] -quiet

# IP: bd/audio_processing/ip/audio_processing_ssd1306_driver_0_0/audio_processing_ssd1306_driver_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_processing_ssd1306_driver_0_0 || ORIG_REF_NAME==audio_processing_ssd1306_driver_0_0} -quiet] -quiet

# IP: bd/audio_processing/ip/audio_processing_axis_audio_delay_0_0/audio_processing_axis_audio_delay_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_processing_axis_audio_delay_0_0 || ORIG_REF_NAME==audio_processing_axis_audio_delay_0_0} -quiet] -quiet

# IP: bd/audio_processing/ip/audio_processing_axi_gpio_0_0/audio_processing_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_processing_axi_gpio_0_0 || ORIG_REF_NAME==audio_processing_axi_gpio_0_0} -quiet] -quiet

# IP: bd/audio_processing/ip/audio_processing_xlslice_0_0/audio_processing_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_processing_xlslice_0_0 || ORIG_REF_NAME==audio_processing_xlslice_0_0} -quiet] -quiet

# IP: bd/audio_processing/ip/audio_processing_xlslice_0_1/audio_processing_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_processing_xlslice_0_1 || ORIG_REF_NAME==audio_processing_xlslice_0_1} -quiet] -quiet

# IP: bd/audio_processing/ip/audio_processing_axi_gpio_0_1/audio_processing_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_processing_axi_gpio_0_1 || ORIG_REF_NAME==audio_processing_axi_gpio_0_1} -quiet] -quiet

# IP: bd/audio_processing/ip/audio_processing_axis_audio_distortion_0_0/audio_processing_axis_audio_distortion_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_processing_axis_audio_distortion_0_0 || ORIG_REF_NAME==audio_processing_axis_audio_distortion_0_0} -quiet] -quiet

# IP: bd/audio_processing/ip/audio_processing_xlslice_0_2/audio_processing_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_processing_xlslice_0_2 || ORIG_REF_NAME==audio_processing_xlslice_0_2} -quiet] -quiet

# IP: bd/audio_processing/ip/audio_processing_axis_audio_tremolo_0_0/audio_processing_axis_audio_tremolo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_processing_axis_audio_tremolo_0_0 || ORIG_REF_NAME==audio_processing_axis_audio_tremolo_0_0} -quiet] -quiet

# IP: bd/audio_processing/ip/audio_processing_xlslice_2_0/audio_processing_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_processing_xlslice_2_0 || ORIG_REF_NAME==audio_processing_xlslice_2_0} -quiet] -quiet

# IP: bd/audio_processing/ip/audio_processing_axis_audio_filter_0_0/audio_processing_axis_audio_filter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_processing_axis_audio_filter_0_0 || ORIG_REF_NAME==audio_processing_axis_audio_filter_0_0} -quiet] -quiet

# IP: bd/audio_processing/ip/audio_processing_xlslice_3_0/audio_processing_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_processing_xlslice_3_0 || ORIG_REF_NAME==audio_processing_xlslice_3_0} -quiet] -quiet

# IP: bd/audio_processing/ip/audio_processing_auto_pc_0/audio_processing_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_processing_auto_pc_0 || ORIG_REF_NAME==audio_processing_auto_pc_0} -quiet] -quiet

# XDC: bd/audio_processing/audio_processing_ooc.xdc
