# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/maniek/Vivado/audio-effect-box/audio-effect-box.srcs/sources_1/bd/audio_processing/ip/audio_processing_axi_gpio_0_1/audio_processing_axi_gpio_0_1.xci
# IP: The module: 'audio_processing_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/maniek/Vivado/audio-effect-box/audio-effect-box.srcs/sources_1/bd/audio_processing/ip/audio_processing_axi_gpio_0_1/audio_processing_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_processing_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/maniek/Vivado/audio-effect-box/audio-effect-box.srcs/sources_1/bd/audio_processing/ip/audio_processing_axi_gpio_0_1/audio_processing_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_processing_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/maniek/Vivado/audio-effect-box/audio-effect-box.srcs/sources_1/bd/audio_processing/ip/audio_processing_axi_gpio_0_1/audio_processing_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_processing_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/maniek/Vivado/audio-effect-box/audio-effect-box.srcs/sources_1/bd/audio_processing/ip/audio_processing_axi_gpio_0_1/audio_processing_axi_gpio_0_1.xci
# IP: The module: 'audio_processing_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/maniek/Vivado/audio-effect-box/audio-effect-box.srcs/sources_1/bd/audio_processing/ip/audio_processing_axi_gpio_0_1/audio_processing_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_processing_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/maniek/Vivado/audio-effect-box/audio-effect-box.srcs/sources_1/bd/audio_processing/ip/audio_processing_axi_gpio_0_1/audio_processing_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_processing_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/maniek/Vivado/audio-effect-box/audio-effect-box.srcs/sources_1/bd/audio_processing/ip/audio_processing_axi_gpio_0_1/audio_processing_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_processing_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
